# Generated by Django 4.2.25 on 2026-01-07 12:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0012_add_documento_servicio_solicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control_acceso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incumplimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('documentacion_invalida', 'Documentación Inválida o Vencida'), ('personal_no_autorizado', 'Personal No Autorizado'), ('vehiculo_no_autorizado', 'Vehículo No Autorizado'), ('horario_incumplido', 'Incumplimiento de Horario Autorizado'), ('zona_no_autorizada', 'Acceso a Zona No Autorizada'), ('seguridad', 'Incumplimiento de Normas de Seguridad'), ('otro', 'Otro Incumplimiento')], max_length=30, verbose_name='Tipo de Incumplimiento')),
                ('descripcion', models.TextField(help_text='Detalle completo de la situación observada', verbose_name='Descripción del Incumplimiento')),
                ('estado', models.CharField(choices=[('reportado', 'Reportado'), ('en_revision', 'En Revisión'), ('pendiente_subsanacion', 'Pendiente de Subsanación'), ('subsanado', 'Subsanado'), ('desestimado', 'Desestimado')], default='reportado', max_length=25, verbose_name='Estado')),
                ('evidencia', models.FileField(blank=True, help_text='Archivo con evidencia del incumplimiento (PDF, imagen o documento)', null=True, upload_to='incumplimientos/evidencias/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])], verbose_name='Evidencia')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el incumplimiento', verbose_name='Observaciones')),
                ('fecha_incumplimiento', models.DateTimeField(help_text='Fecha y hora en que ocurrió el incumplimiento', verbose_name='Fecha del Incumplimiento')),
                ('fecha_reporte', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Reporte')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('autorizacion', models.ForeignKey(blank=True, help_text='Autorización asociada si ya fue aprobada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incumplimientos', to='control_acceso.autorizacion', verbose_name='Autorización Relacionada')),
                ('lugar_puerto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incumplimientos', to='solicitudes.lugarpuerto', verbose_name='Lugar Específico')),
                ('puerto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incumplimientos', to='solicitudes.puerto', verbose_name='Puerto')),
                ('reportado_por', models.ForeignKey(help_text='Oficial de acceso que detectó el incumplimiento', on_delete=django.db.models.deletion.PROTECT, related_name='incumplimientos_reportados', to=settings.AUTH_USER_MODEL, verbose_name='Reportado Por')),
                ('revisado_por', models.ForeignKey(blank=True, help_text='Supervisor que revisó el incumplimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incumplimientos_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por')),
                ('solicitud', models.ForeignKey(help_text='Solicitud asociada al incumplimiento', on_delete=django.db.models.deletion.CASCADE, related_name='incumplimientos', to='solicitudes.solicitud', verbose_name='Solicitud Relacionada')),
            ],
            options={
                'verbose_name': 'Incumplimiento',
                'verbose_name_plural': 'Incumplimientos',
                'ordering': ['-fecha_incumplimiento', '-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudSubsanacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacion_requerida', models.TextField(help_text='Detalle específico de qué debe presentar la empresa para subsanar', verbose_name='Información/Documentación Requerida')),
                ('plazo_dias', models.PositiveIntegerField(default=5, help_text='Cantidad de días hábiles para responder', verbose_name='Plazo en Días Hábiles')),
                ('fecha_limite', models.DateTimeField(help_text='Fecha y hora límite para responder (calculada automáticamente)', verbose_name='Fecha Límite')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Respuesta'), ('respondida', 'Respondida por Empresa'), ('aprobada', 'Subsanación Aprobada'), ('rechazada', 'Subsanación Rechazada'), ('vencida', 'Plazo Vencido')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Solicitud')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('incumplimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_subsanacion', to='incumplimientos.incumplimiento', verbose_name='Incumplimiento')),
                ('solicitado_por', models.ForeignKey(help_text='Supervisor que solicita la subsanación', on_delete=django.db.models.deletion.PROTECT, related_name='subsanaciones_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado Por')),
            ],
            options={
                'verbose_name': 'Solicitud de Subsanación',
                'verbose_name_plural': 'Solicitudes de Subsanación',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaSubsanacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explicacion', models.TextField(help_text='Explicación de las medidas correctivas implementadas', verbose_name='Explicación')),
                ('medidas_preventivas', models.TextField(blank=True, help_text='Medidas implementadas para prevenir futuros incumplimientos', verbose_name='Medidas Preventivas')),
                ('estado', models.CharField(choices=[('enviada', 'Enviada - Pendiente de Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada - Requiere Corrección')], default='enviada', max_length=20, verbose_name='Estado')),
                ('comentarios_revision', models.TextField(blank=True, help_text='Comentarios del supervisor sobre la respuesta', verbose_name='Comentarios de Revisión')),
                ('fecha_respuesta', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Respuesta')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('respondido_por', models.ForeignKey(help_text='Usuario de la empresa que envía la respuesta', on_delete=django.db.models.deletion.PROTECT, related_name='subsanaciones_respondidas', to=settings.AUTH_USER_MODEL, verbose_name='Respondido Por')),
                ('revisado_por', models.ForeignKey(blank=True, help_text='Supervisor que revisa la respuesta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsanaciones_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por')),
                ('solicitud_subsanacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='incumplimientos.solicitudsubsanacion', verbose_name='Solicitud de Subsanación')),
            ],
            options={
                'verbose_name': 'Respuesta de Subsanación',
                'verbose_name_plural': 'Respuestas de Subsanación',
                'ordering': ['-fecha_respuesta'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoSubsanacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('certificado', 'Certificado'), ('licencia', 'Licencia'), ('foto', 'Fotografía'), ('informe', 'Informe'), ('acta', 'Acta'), ('otro', 'Otro Documento')], max_length=20, verbose_name='Tipo de Documento')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Documento')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del documento', verbose_name='Descripción')),
                ('archivo', models.FileField(help_text='Documento de soporte (PDF, imagen o documento Word)', upload_to='incumplimientos/subsanaciones/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])], verbose_name='Archivo')),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Subida')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='incumplimientos.respuestasubsanacion', verbose_name='Respuesta de Subsanación')),
            ],
            options={
                'verbose_name': 'Documento de Subsanación',
                'verbose_name_plural': 'Documentos de Subsanación',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AddIndex(
            model_name='incumplimiento',
            index=models.Index(fields=['solicitud', 'estado'], name='incumplimie_solicit_5b4afc_idx'),
        ),
        migrations.AddIndex(
            model_name='incumplimiento',
            index=models.Index(fields=['reportado_por', 'fecha_reporte'], name='incumplimie_reporta_ab1503_idx'),
        ),
        migrations.AddIndex(
            model_name='incumplimiento',
            index=models.Index(fields=['estado'], name='incumplimie_estado_1f0a1a_idx'),
        ),
    ]
