# Generated by Django 4.2.25 on 2026-01-06 13:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proveedor', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('custom', 'SMTP Personalizado')], default='custom', help_text='Seleccione su proveedor de correo para autoconfigurar los valores', max_length=20, verbose_name='Tipo de Proveedor')),
                ('nombre', models.CharField(default='Configuración Principal', help_text='Nombre para identificar esta configuración', max_length=100, verbose_name='Nombre de la Configuración')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', help_text='Backend de email a utilizar', max_length=100, verbose_name='Backend de Email')),
                ('email_host', models.CharField(default='smtp.gmail.com', help_text='Dirección del servidor SMTP (ej: smtp.gmail.com)', max_length=100, verbose_name='Servidor SMTP')),
                ('email_port', models.PositiveIntegerField(default=587, help_text='Puerto del servidor SMTP (587 para TLS, 465 para SSL, 25 sin cifrado)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Puerto SMTP')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Usar cifrado TLS (recomendado para puerto 587)', verbose_name='Usar TLS')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Usar cifrado SSL (para puerto 465)', verbose_name='Usar SSL')),
                ('email_host_user', models.EmailField(help_text='Dirección de email para autenticación SMTP', max_length=254, verbose_name='Usuario de Email')),
                ('email_host_password', models.CharField(help_text='Contraseña o App Password para autenticación SMTP', max_length=200, verbose_name='Contraseña de Email')),
                ('default_from_email', models.EmailField(help_text='Dirección de email que aparecerá como remitente', max_length=254, verbose_name='Email Remitente')),
                ('password_reset_timeout', models.PositiveIntegerField(default=24, help_text='Horas de validez para los enlaces de recuperación de contraseña', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='Tiempo de expiración (horas)')),
                ('max_reset_attempts', models.PositiveIntegerField(default=3, help_text='Máximo número de solicitudes de recuperación por email por hora', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Máx. intentos por hora')),
                ('reset_email_subject', models.CharField(default='NaviPort RD - Recuperación de Contraseña', max_length=200, verbose_name='Asunto del Email de Recuperación')),
                ('email_enabled', models.BooleanField(default=False, help_text='Habilitar el envío de emails (recuperación de contraseñas, notificaciones)', verbose_name='Sistema de Email Habilitado')),
                ('test_email_sent', models.BooleanField(default=False, help_text='Indica si se ha enviado exitosamente un email de prueba', verbose_name='Email de Prueba Enviado')),
                ('last_test_date', models.DateTimeField(blank=True, null=True, verbose_name='Última Prueba de Email')),
                ('total_emails_sent', models.PositiveIntegerField(default=0, help_text='Contador de emails enviados con esta configuración', verbose_name='Total de Emails Enviados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Configuración de Email',
                'verbose_name_plural': 'Configuraciones de Email',
            },
        ),
        migrations.CreateModel(
            name='EventoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('solicitud_recibida', 'Solicitud Recibida'), ('solicitud_aprobada', 'Solicitud Aprobada'), ('solicitud_rechazada', 'Solicitud Rechazada'), ('solicitud_requerimientos', 'Solicitud con Requerimientos'), ('solicitud_vencida', 'Solicitud Vencida'), ('asignacion_evaluador', 'Asignación a Evaluador'), ('asignacion_supervisor', 'Asignación a Supervisor'), ('autorizacion_generada', 'Autorización Generada'), ('autorizacion_vencida', 'Autorización Vencida'), ('extension_solicitada', 'Extensión de Validez Solicitada'), ('extension_aprobada', 'Extensión de Validez Aprobada'), ('extension_rechazada', 'Extensión de Validez Rechazada'), ('incumplimiento_reportado', 'Incumplimiento Reportado'), ('subsanacion_solicitada', 'Subsanación Solicitada'), ('subsanacion_respondida', 'Subsanación Respondida'), ('solicitud_excepcional_aprobada', 'Solicitud Excepcional Aprobada'), ('licencia_por_vencer', 'Licencia por Vencer'), ('licencia_vencida', 'Licencia Vencida'), ('contrato_por_vencer', 'Contrato por Vencer'), ('contrato_vencido', 'Contrato Vencido'), ('personalizado', 'Evento Personalizado')], help_text='Código único que identifica este evento', max_length=50, unique=True, verbose_name='Código del Evento')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del evento', max_length=100, verbose_name='Nombre del Evento')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del evento', verbose_name='Descripción')),
                ('asunto_email', models.CharField(help_text='Puede usar variables: {solicitud_codigo}, {empresa_nombre}, {usuario_nombre}', max_length=200, verbose_name='Asunto del Email')),
                ('template_html', models.CharField(blank=True, help_text='Nombre del archivo template (ej: emails/solicitud_recibida.html)', max_length=200, verbose_name='Template HTML')),
                ('mensaje_texto_plano', models.TextField(blank=True, help_text='Versión en texto plano del mensaje. Puede usar variables.', verbose_name='Mensaje en Texto Plano')),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado, no se enviarán notificaciones para este evento', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Evento del Sistema',
                'verbose_name_plural': 'Eventos del Sistema',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LogNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatarios', models.TextField(help_text='Lista de emails separados por comas', verbose_name='Destinatarios')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto')),
                ('mensaje_html', models.TextField(blank=True, verbose_name='Mensaje HTML')),
                ('mensaje_texto', models.TextField(blank=True, verbose_name='Mensaje en Texto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('exitoso', models.BooleanField(default=False, verbose_name='Envío Exitoso')),
                ('mensaje_error', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional (solicitud_id, empresa_id, etc.)', verbose_name='Metadata')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='notificaciones.eventosistema', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Log de Notificación',
                'verbose_name_plural': 'Logs de Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DestinatarioEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_destinatario', models.CharField(choices=[('rol', 'Por Rol'), ('email', 'Email Específico')], default='rol', max_length=20, verbose_name='Tipo de Destinatario')),
                ('rol', models.CharField(blank=True, choices=[('evaluador', 'Evaluadores'), ('supervisor', 'Supervisores'), ('direccion', 'Dirección Logística'), ('admin_tic', 'Administradores TIC'), ('oficial_acceso', 'Oficiales de Acceso'), ('empresa', 'Empresa (solicitante)'), ('evaluador_asignado', 'Evaluador Asignado (específico)'), ('supervisor_asignado', 'Supervisor Asignado (específico)')], help_text='Rol que recibirá la notificación', max_length=30, null=True, verbose_name='Rol')),
                ('email_especifico', models.EmailField(blank=True, help_text='Email individual que recibirá la notificación', max_length=254, null=True, verbose_name='Email Específico')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='notificaciones.eventosistema', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Destinatario de Evento',
                'verbose_name_plural': 'Destinatarios de Eventos',
                'ordering': ['evento', 'tipo_destinatario', 'rol'],
            },
        ),
    ]
