# Generated by Django 5.2.1 on 2025-09-29 12:26

import django.db.models.deletion
import gestion_vehiculos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Formato: A123456 o AB123456', max_length=8, unique=True, validators=[gestion_vehiculos.models.validate_placa_dominicana])),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.PositiveIntegerField(help_text='Año del vehículo (ej: 2020)')),
                ('color', models.CharField(max_length=30)),
                ('tipo_vehiculo', models.CharField(choices=[('automovil', 'Automóvil'), ('camion', 'Camión'), ('camioneta', 'Camioneta'), ('motocicleta', 'Motocicleta'), ('autobus', 'Autobús'), ('trailer', 'Trailer'), ('montacargas', 'Montacargas'), ('otro', 'Otro')], max_length=20)),
                ('numero_chasis', models.CharField(blank=True, help_text='Número de chasis (VIN)', max_length=50, null=True)),
                ('numero_motor', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa_propietaria', models.ForeignKey(blank=True, help_text='Empresa propietaria del vehículo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'gestion_vehiculos_vehiculo',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('matricula', 'Matrícula'), ('registro', 'Registro'), ('seguro', 'Seguro'), ('revision_tecnica', 'Revisión Técnica'), ('permiso_circulacion', 'Permiso de Circulación'), ('otro', 'Otro Documento')], max_length=20)),
                ('numero_documento', models.CharField(blank=True, help_text='Número del documento (opcional)', max_length=50, null=True)),
                ('archivo', models.FileField(help_text='Archivo del documento (PDF, JPG, PNG máx. 5MB)', upload_to='documentos/vehiculos/%Y/%m/')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento del documento', null=True)),
                ('estado_validacion', models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('validado', 'Validado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('comentarios_validacion', models.TextField(blank=True, null=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_vehiculos_subidos', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_vehiculos_validados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion_vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Documento de Vehículo',
                'verbose_name_plural': 'Documentos de Vehículos',
                'db_table': 'gestion_vehiculos_documento',
                'ordering': ['-fecha_subida'],
                'unique_together': {('vehiculo', 'tipo_documento')},
            },
        ),
    ]
