# Generated by Django 4.2.25 on 2026-01-27 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_inhabilitacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se inhabilitó el vehículo', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='inhabilitado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que inhabilitó el vehículo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_inhabilitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='motivo_inhabilitacion',
            field=models.TextField(blank=True, help_text='Motivo por el cual se inhabilitó el vehículo', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='notas_adicionales',
            field=models.TextField(blank=True, help_text='Notas o comentarios adicionales sobre el vehículo', null=True),
        ),
    ]
