# Generated by Django 5.2.1 on 2025-08-18 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_preaviso_critico', models.PositiveIntegerField(default=30, help_text='Días antes de expiración para considerar crítico (ej: 30 días)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Días de preaviso crítico')),
                ('dias_preaviso_advertencia', models.PositiveIntegerField(default=60, help_text='Días antes de expiración para mostrar advertencia (ej: 60 días)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Días de preaviso de advertencia')),
                ('dias_preaviso_informativo', models.PositiveIntegerField(default=90, help_text='Días antes de expiración para mostrar información (ej: 90 días)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Días de preaviso informativo')),
                ('tipo_expiracion_principal', models.CharField(choices=[('vuce', 'Fecha de Expiración VUCE'), ('contrato', 'Expiración Contrato'), ('ambas', 'Ambas fechas (la más próxima)')], default='vuce', max_length=10, verbose_name='Expiración principal a considerar')),
                ('notificar_empresas_vencidas', models.BooleanField(default=True, verbose_name='Notificar empresas con licencias vencidas')),
                ('permitir_solicitudes_vencidas', models.BooleanField(default=False, verbose_name='Permitir solicitudes de empresas con licencias vencidas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Configuración de Evaluación',
                'verbose_name_plural': 'Configuraciones de Evaluación',
            },
        ),
    ]
