# Generated by Django 5.2.1 on 2025-08-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionevaluacion',
            name='enlace_instrucciones',
            field=models.URLField(blank=True, help_text='URL que aparecerá en los avisos de expiración (ej: https://vuce.gob.do/renovacion)', null=True, verbose_name='Enlace de instrucciones para renovación'),
        ),
    ]
