# Generated by Django 5.2.1 on 2025-08-18 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_configuracionevaluacion_enlace_instrucciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionevaluacion',
            name='tiempo_respuesta_horas',
            field=models.PositiveIntegerField(default=24, help_text='Tiempo límite para responder solicitudes en horas (máximo 7 días)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='Tiempo de respuesta (horas)'),
        ),
    ]
