# Generated by Django 5.2.1 on 2025-08-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0003_configuracionevaluacion_tiempo_respuesta_horas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Carga General, Contenedores, Combustibles, etc.', max_length=100, unique=True, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del servicio', verbose_name='Descripción')),
                ('codigo', models.CharField(help_text='Código único del servicio (ej: CG-001)', max_length=20, unique=True, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado, no aparecerá en nuevas asignaciones', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Licencia Portuaria General, Licencia de Combustibles, etc.', max_length=100, unique=True, verbose_name='Nombre del Tipo de Licencia')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del tipo de licencia y sus alcances', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado, no aparecerá en nuevas asignaciones', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('servicios_incluidos', models.ManyToManyField(blank=True, help_text='Servicios que se autorizan automáticamente con este tipo de licencia', related_name='tipos_licencia', to='evaluacion.servicio', verbose_name='Servicios Incluidos')),
            ],
            options={
                'verbose_name': 'Tipo de Licencia',
                'verbose_name_plural': 'Tipos de Licencia',
                'ordering': ['nombre'],
            },
        ),
    ]
