# Generated by Django 5.2.1 on 2025-09-08 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0004_servicio_tipolicencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', help_text='Backend de email a utilizar', max_length=100, verbose_name='Backend de Email')),
                ('email_host', models.CharField(default='smtp.gmail.com', help_text='Dirección del servidor SMTP (ej: smtp.gmail.com)', max_length=100, verbose_name='Servidor SMTP')),
                ('email_port', models.PositiveIntegerField(default=587, help_text='Puerto del servidor SMTP (587 para TLS, 465 para SSL, 25 sin cifrado)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Puerto SMTP')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Usar cifrado TLS (recomendado para puerto 587)', verbose_name='Usar TLS')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Usar cifrado SSL (para puerto 465)', verbose_name='Usar SSL')),
                ('email_host_user', models.EmailField(help_text='Dirección de email para autenticación SMTP', max_length=254, verbose_name='Usuario de Email')),
                ('email_host_password', models.CharField(help_text='Contraseña o App Password para autenticación SMTP', max_length=200, verbose_name='Contraseña de Email')),
                ('default_from_email', models.EmailField(help_text='Dirección de email que aparecerá como remitente', max_length=254, verbose_name='Email Remitente')),
                ('password_reset_timeout', models.PositiveIntegerField(default=24, help_text='Horas de validez para los enlaces de recuperación de contraseña', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='Tiempo de expiración (horas)')),
                ('max_reset_attempts', models.PositiveIntegerField(default=3, help_text='Máximo número de solicitudes de recuperación por email por hora', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Máx. intentos por hora')),
                ('reset_email_subject', models.CharField(default='NaviPort RD - Recuperación de Contraseña', max_length=200, verbose_name='Asunto del Email de Recuperación')),
                ('email_enabled', models.BooleanField(default=False, help_text='Habilitar el envío de emails (recuperación de contraseñas, notificaciones)', verbose_name='Sistema de Email Habilitado')),
                ('test_email_sent', models.BooleanField(default=False, help_text='Indica si se ha enviado exitosamente un email de prueba', verbose_name='Email de Prueba Enviado')),
                ('last_test_date', models.DateTimeField(blank=True, null=True, verbose_name='Última Prueba de Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Configuración de Email',
                'verbose_name_plural': 'Configuración de Email',
            },
        ),
    ]
