# Generated by Django 5.2.1 on 2025-09-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0005_configuracionemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionemail',
            name='nombre',
            field=models.CharField(default='Configuración Principal', help_text='Nombre para identificar esta configuración', max_length=100, verbose_name='Nombre de la Configuración'),
        ),
        migrations.AddField(
            model_name='configuracionemail',
            name='tipo_proveedor',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('custom', 'SMTP Personalizado')], default='custom', help_text='Seleccione su proveedor de correo para autoconfigurar los valores', max_length=20, verbose_name='Tipo de Proveedor'),
        ),
        migrations.AddField(
            model_name='configuracionemail',
            name='total_emails_sent',
            field=models.PositiveIntegerField(default=0, help_text='Contador de emails enviados con esta configuración', verbose_name='Total de Emails Enviados'),
        ),
    ]
