# Generated by Django 5.2.4 on 2025-11-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0006_configuracionemail_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionemail',
            name='correos_notificaciones',
            field=models.TextField(blank=True, help_text='Lista de correos separados por comas que recibirán notificaciones de nuevas solicitudes (ej: admin@mail.com, supervisor@mail.com)', null=True, verbose_name='Correos de Notificación'),
        ),
    ]
