# Generated by Django 4.2.25 on 2025-11-20 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0007_configuracionemail_correos_notificaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionevaluacion',
            name='permitir_solicitudes_vencidas',
        ),
    ]
