# Generated by Django 4.2.16 on 2025-11-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0008_eliminar_permitir_solicitudes_vencidas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRequeridoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Certificado de Fumigación, Factura Comercial, etc.', max_length=150, verbose_name='Nombre del Documento')),
                ('descripcion', models.TextField(blank=True, help_text='Instrucciones adicionales sobre el documento requerido', verbose_name='Descripción/Instrucciones')),
                ('obligatorio', models.BooleanField(default=True, help_text='Si está marcado, el solicitante debe adjuntar este documento', verbose_name='Obligatorio')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el formulario', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_requeridos', to='evaluacion.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Documento Requerido',
                'verbose_name_plural': 'Documentos Requeridos',
                'ordering': ['servicio', 'orden', 'nombre'],
            },
        ),
    ]
