# Generated by Django 4.2.16 on 2025-07-29 18:32

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('solicitante', 'Solicitante'), ('evaluador', 'Evaluador Portuario'), ('supervisor', 'Supervisor'), ('admin_tic', 'Administrador TIC'), ('oficial_acceso', 'Oficial de Acceso Físico'), ('direccion', 'Dirección Logística')], default='solicitante', max_length=20, verbose_name='Rol')),
                ('cedula_rnc', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use XXX-XXXXXXX-X para cédula o XXX-XXXXX-X para RNC', regex='^(\\d{3}-\\d{7}-\\d{1}|\\d{3}-\\d{5}-\\d{1})$')], verbose_name='Cédula/RNC')),
                ('telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Número de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('empresa_nombre', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='Intentos fallidos')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado hasta')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Última IP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnc', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use XXX-XXXXX-X para RNC', regex='^\\d{3}-\\d{5}-\\d{1}$')], verbose_name='RNC')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Número de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('verificada', models.BooleanField(default=False, verbose_name='Verificada')),
                ('certificado_rnc', models.FileField(blank=True, upload_to='empresas/certificados/', verbose_name='Certificado RNC')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('representante_legal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_representadas', to=settings.AUTH_USER_MODEL, verbose_name='Representante Legal')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-created_at'],
            },
        ),
    ]
