# Generated by Django 5.2.1 on 2025-08-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_empresa_nombre_user_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fecha_expedicion_licencia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Expedición'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_expiracion_licencia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Expiración'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_licencia',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de Licencia'),
        ),
    ]
