# Generated by Django 5.2.1 on 2025-08-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_empresa_fecha_expedicion_licencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fecha_expiracion_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Expiración Contrato'),
        ),
    ]
