# Generated by Django 5.2.1 on 2025-08-18 18:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_empresa_fecha_expiracion_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('critico', 'Crítico'), ('advertencia', 'Advertencia'), ('informativo', 'Informativo'), ('vencido', 'Vencido')], max_length=15, verbose_name='Tipo de Notificación')),
                ('categoria', models.CharField(choices=[('vuce', 'Expiración VUCE'), ('contrato', 'Expiración Contrato'), ('general', 'General')], default='general', max_length=15, verbose_name='Categoría')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('enlace_accion', models.URLField(blank=True, null=True, verbose_name='Enlace de Acción')),
                ('texto_enlace', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto del Enlace')),
                ('fecha_expiracion', models.DateField(blank=True, null=True, verbose_name='Fecha de Expiración Relacionada')),
                ('mostrar_desde', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mostrar Desde')),
                ('mostrar_hasta', models.DateTimeField(blank=True, null=True, verbose_name='Mostrar Hasta')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('cerrada_por_usuario', models.BooleanField(default=False, verbose_name='Cerrada por Usuario')),
                ('fecha_cerrada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='accounts.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación de Empresa',
                'verbose_name_plural': 'Notificaciones de Empresas',
                'ordering': ['-created_at', 'tipo'],
                'indexes': [models.Index(fields=['usuario', 'activa', 'cerrada_por_usuario'], name='accounts_no_usuario_a85cb6_idx'), models.Index(fields=['empresa', 'tipo'], name='accounts_no_empresa_237077_idx')],
            },
        ),
    ]
