# Generated by Django 5.2.1 on 2025-08-19 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notificacionempresa'),
        ('evaluacion', '0004_servicio_tipolicencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='servicios_autorizados',
            field=models.ManyToManyField(blank=True, help_text='Servicios específicos que la empresa está autorizada a ofrecer', related_name='empresas_autorizadas', to='evaluacion.servicio', verbose_name='Servicios Autorizados'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_licencia',
            field=models.ForeignKey(blank=True, help_text='Tipo de licencia que determina los servicios base autorizados', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_asignadas', to='evaluacion.tipolicencia', verbose_name='Tipo de Licencia'),
        ),
    ]
