# Generated by Django 5.2.1 on 2025-09-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_empresa_servicios_autorizados_empresa_tipo_licencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='es_admin_empresa',
            field=models.BooleanField(default=False, verbose_name='Admin de Empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='puede_crear_usuarios',
            field=models.BooleanField(default=False, verbose_name='Puede Crear Usuarios'),
        ),
    ]
