# Generated by Django 4.2.25 on 2026-01-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_es_admin_empresa_user_puede_crear_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='puede_solicitud_excepcional',
            field=models.BooleanField(default=False, help_text='Si está habilitado, la empresa puede realizar solicitudes excepcionales aprobadas por supervisión', verbose_name='Permite Solicitud Excepcional'),
        ),
    ]
