# Generated by Django 4.2.25 on 2026-01-07 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_empresa_puede_solicitud_excepcional'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprobacionExcepcional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(help_text='Justificación detallada de por qué se aprueba la solicitud excepcional', verbose_name='Motivo de la Aprobación')),
                ('fecha_aprobacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Aprobación')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('revocada', 'Revocada'), ('vencida', 'Vencida')], default='activa', max_length=10, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha desde la cual es válida la aprobación', null=True, verbose_name='Fecha de Inicio')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha hasta la cual es válida la aprobación (dejar vacío para indefinido)', null=True, verbose_name='Fecha de Vencimiento')),
                ('fecha_revocacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revocación')),
                ('motivo_revocacion', models.TextField(blank=True, help_text='Razón por la cual se revocó la aprobación', verbose_name='Motivo de Revocación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones Adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('aprobada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_excepcionales_otorgadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobada por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones_excepcionales', to='accounts.empresa', verbose_name='Empresa')),
                ('revocada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_excepcionales_revocadas', to=settings.AUTH_USER_MODEL, verbose_name='Revocada por')),
            ],
            options={
                'verbose_name': 'Aprobación Excepcional',
                'verbose_name_plural': 'Aprobaciones Excepcionales',
                'ordering': ['-fecha_aprobacion'],
                'indexes': [models.Index(fields=['empresa', 'estado'], name='accounts_ap_empresa_28470f_idx'), models.Index(fields=['aprobada_por', '-fecha_aprobacion'], name='accounts_ap_aprobad_9c226f_idx')],
            },
        ),
    ]
