# Generated by Django 5.2.1 on 2025-09-29 12:26

import django.db.models.deletion
import gestion_personal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(help_text='Formato: XXX-XXXXXXX-X', max_length=13, unique=True, validators=[gestion_personal.models.validate_cedula_dominicana])),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa que registró esta persona', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'gestion_personal_persona',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('cedula', 'Cédula de Identidad'), ('licencia_conducir', 'Licencia de Conducir'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro Documento')], max_length=20)),
                ('numero_documento', models.CharField(blank=True, help_text='Número del documento (opcional)', max_length=50, null=True)),
                ('archivo', models.FileField(help_text='Archivo del documento (PDF, JPG, PNG máx. 5MB)', upload_to='documentos/personal/%Y/%m/')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento del documento', null=True)),
                ('estado_validacion', models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('validado', 'Validado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('comentarios_validacion', models.TextField(blank=True, null=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_personales_subidos', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_personales_validados', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion_personal.persona')),
            ],
            options={
                'verbose_name': 'Documento Personal',
                'verbose_name_plural': 'Documentos Personales',
                'db_table': 'gestion_personal_documento',
                'ordering': ['-fecha_subida'],
                'unique_together': {('persona', 'tipo_documento')},
            },
        ),
    ]
