# Generated by Django 5.2.4 on 2025-11-20 03:27

import gestion_personal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(help_text='Formato: XXX-XXXXXXX-X', max_length=13, validators=[gestion_personal.models.validate_cedula_dominicana]),
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('cedula', 'empresa')},
        ),
    ]
