# Generated by Django 4.2.25 on 2026-01-07 14:59

from django.db import migrations, models
import gestion_personal.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personal', '0002_alter_persona_cedula_alter_persona_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='pasaporte',
            field=models.CharField(blank=True, help_text='Número de pasaporte (para extranjeros sin cédula)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(blank=True, help_text='Formato: XXX-XXXXXXX-X (para dominicanos)', max_length=13, null=True, validators=[gestion_personal.models.validate_cedula_dominicana]),
        ),
    ]
