# Generated by Django 4.2.25 on 2026-01-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personal', '0003_persona_pasaporte_alter_persona_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='cargo',
            field=models.CharField(blank=True, help_text='Ej: Conductor, Operador, Técnico, etc.', max_length=100, null=True, verbose_name='Cargo/Posición'),
        ),
        migrations.AddField(
            model_name='persona',
            name='licencia_conducir',
            field=models.CharField(blank=True, help_text='Número de licencia de conducir si aplica', max_length=20, null=True, verbose_name='Licencia de Conducir'),
        ),
    ]
