# Generated by Django 4.2.16 on 2025-07-29 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Código de Autorización')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID único')),
                ('empresa_nombre', models.CharField(max_length=200, verbose_name='Empresa')),
                ('empresa_rnc', models.CharField(max_length=15, verbose_name='RNC')),
                ('representante_nombre', models.CharField(max_length=200, verbose_name='Representante')),
                ('representante_cedula', models.CharField(max_length=15, verbose_name='Cédula')),
                ('valida_desde', models.DateTimeField(verbose_name='Válida desde')),
                ('valida_hasta', models.DateTimeField(verbose_name='Válida hasta')),
                ('puerto_nombre', models.CharField(max_length=100, verbose_name='Puerto')),
                ('motivo_acceso', models.CharField(max_length=200, verbose_name='Motivo')),
                ('vehiculos_autorizados', models.JSONField(blank=True, default=list, verbose_name='Vehículos Autorizados')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('revocada', 'Revocada'), ('usada', 'Usada')], default='activa', max_length=15, verbose_name='Estado')),
                ('qr_code', models.ImageField(blank=True, upload_to='autorizaciones/qr/%Y/%m/', verbose_name='Código QR')),
                ('creada_el', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('actualizada_el', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('revocada_el', models.DateTimeField(blank=True, null=True, verbose_name='Revocada el')),
                ('motivo_revocacion', models.TextField(blank=True, verbose_name='Motivo de Revocación')),
                ('generada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones_generadas', to=settings.AUTH_USER_MODEL, verbose_name='Generada por')),
                ('revocada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones_revocadas', to=settings.AUTH_USER_MODEL, verbose_name='Revocada por')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacion', to='solicitudes.solicitud', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Autorización',
                'verbose_name_plural': 'Autorizaciones',
                'ordering': ['-creada_el'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acceso', models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida')], max_length=10, verbose_name='Tipo de Acceso')),
                ('vehiculo_placa', models.CharField(max_length=15, verbose_name='Placa del Vehículo')),
                ('conductor_nombre', models.CharField(max_length=200, verbose_name='Conductor')),
                ('estado', models.CharField(choices=[('autorizado', 'Autorizado'), ('denegado', 'Denegado'), ('pendiente', 'Pendiente Verificación')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('documento_verificado', models.BooleanField(default=False, verbose_name='Documento Verificado')),
                ('vehiculo_verificado', models.BooleanField(default=False, verbose_name='Vehículo Verificado')),
                ('conductor_verificado', models.BooleanField(default=False, verbose_name='Conductor Verificado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('motivo_denegacion', models.TextField(blank=True, verbose_name='Motivo de Denegación')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('autorizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to='control_acceso.autorizacion', verbose_name='Autorización')),
                ('oficial_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_procesados', to=settings.AUTH_USER_MODEL, verbose_name='Oficial de Acceso')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Discrepancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código de Discrepancia')),
                ('tipo_discrepancia', models.CharField(choices=[('vehiculo_diferente', 'Vehículo Diferente'), ('conductor_diferente', 'Conductor Diferente'), ('documento_vencido', 'Documento Vencido'), ('documento_ilegible', 'Documento Ilegible'), ('autorizacion_vencida', 'Autorización Vencida'), ('datos_incorrectos', 'Datos Incorrectos'), ('otros', 'Otros')], max_length=25, verbose_name='Tipo de Discrepancia')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('reportada', 'Reportada'), ('en_revision', 'En Revisión'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], default='reportada', max_length=15, verbose_name='Estado')),
                ('resolucion', models.TextField(blank=True, verbose_name='Resolución')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('creada_el', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('actualizada_el', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('asignada_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancias_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignada a')),
                ('registro_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancias', to='control_acceso.registroacceso', verbose_name='Registro de Acceso')),
                ('reportada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancias_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Reportada por')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancias_resueltas', to=settings.AUTH_USER_MODEL, verbose_name='Resuelta por')),
            ],
            options={
                'verbose_name': 'Discrepancia',
                'verbose_name_plural': 'Discrepancias',
                'ordering': ['-creada_el'],
            },
        ),
        migrations.AddIndex(
            model_name='registroacceso',
            index=models.Index(fields=['autorizacion', 'tipo_acceso'], name='control_acc_autoriz_2c6fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='registroacceso',
            index=models.Index(fields=['-timestamp'], name='control_acc_timesta_8b09e4_idx'),
        ),
        migrations.AddIndex(
            model_name='registroacceso',
            index=models.Index(fields=['oficial_acceso', '-timestamp'], name='control_acc_oficial_56df45_idx'),
        ),
        migrations.AddIndex(
            model_name='autorizacion',
            index=models.Index(fields=['codigo'], name='control_acc_codigo_6f184d_idx'),
        ),
        migrations.AddIndex(
            model_name='autorizacion',
            index=models.Index(fields=['uuid'], name='control_acc_uuid_c47e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='autorizacion',
            index=models.Index(fields=['estado', '-creada_el'], name='control_acc_estado_a4194c_idx'),
        ),
    ]
