# Generated by Django 4.2.25 on 2026-01-07 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control_acceso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código de Extensión')),
                ('fecha_vencimiento_actual', models.DateTimeField(help_text='Fecha actual de vencimiento de la autorización', verbose_name='Fecha de Vencimiento Actual')),
                ('fecha_vencimiento_solicitada', models.DateTimeField(help_text='Nueva fecha hasta la cual se solicita extender la autorización', verbose_name='Nueva Fecha de Vencimiento Solicitada')),
                ('motivo', models.TextField(help_text='Justificación detallada del por qué se necesita la extensión', verbose_name='Motivo de la Extensión')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('observaciones_respuesta', models.TextField(blank=True, help_text='Comentarios del supervisor/dirección al aprobar o rechazar', verbose_name='Observaciones de la Respuesta')),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Razón por la cual se rechaza la extensión', verbose_name='Motivo del Rechazo')),
                ('creada_el', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('actualizada_el', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('autorizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_extension', to='control_acceso.autorizacion', verbose_name='Autorización')),
                ('procesada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extensiones_procesadas', to=settings.AUTH_USER_MODEL, verbose_name='Procesada por')),
                ('solicitada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensiones_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitada por')),
            ],
            options={
                'verbose_name': 'Solicitud de Extensión',
                'verbose_name_plural': 'Solicitudes de Extensión',
                'ordering': ['-creada_el'],
                'indexes': [models.Index(fields=['estado', '-creada_el'], name='control_acc_estado_9711fd_idx'), models.Index(fields=['autorizacion'], name='control_acc_autoriz_6a54ff_idx'), models.Index(fields=['solicitada_por'], name='control_acc_solicit_826748_idx')],
            },
        ),
    ]
