# Generated by Django 4.2.16 on 2025-07-29 18:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Motivo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('requiere_documentos_especiales', models.BooleanField(default=False, verbose_name='Requiere documentos especiales')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Motivo de Acceso',
                'verbose_name_plural': 'Motivos de Acceso',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Puerto',
                'verbose_name_plural': 'Puertos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código de Solicitud')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('hora_ingreso', models.TimeField(verbose_name='Hora de Ingreso')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de Salida')),
                ('hora_salida', models.TimeField(verbose_name='Hora de Salida')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente de Revisión'), ('en_revision', 'En Revisión'), ('documentos_faltantes', 'Documentos Faltantes'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida'), ('escalada', 'Escalada a Supervisor')], default='borrador', max_length=25, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('critica', 'Crítica'), ('vip', 'VIP Gubernamental')], default='normal', max_length=15, verbose_name='Prioridad')),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Evaluación')),
                ('comentarios_evaluacion', models.TextField(blank=True, verbose_name='Comentarios de Evaluación')),
                ('motivo_rechazo', models.TextField(blank=True, verbose_name='Motivo de Rechazo')),
                ('vence_el', models.DateTimeField(blank=True, null=True, verbose_name='Vence el')),
                ('tiempo_limite_horas', models.PositiveIntegerField(default=24, verbose_name='Tiempo límite (horas)')),
                ('creada_el', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('actualizada_el', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('enviada_el', models.DateTimeField(blank=True, null=True, verbose_name='Enviada el')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='accounts.empresa', verbose_name='Empresa')),
                ('evaluador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador Asignado')),
                ('motivo_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.motivoacceso', verbose_name='Motivo del Acceso')),
                ('puerto_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.puerto', verbose_name='Puerto de Destino')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-creada_el'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('cedula_representante', 'Cédula del Representante'), ('rnc_empresa', 'RNC de la Empresa'), ('registro_vehiculo', 'Registro de Vehículo'), ('licencia_conducir', 'Licencia de Conducir'), ('otros', 'Otros Documentos')], max_length=25, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(upload_to='solicitudes/documentos/%Y/%m/', verbose_name='Archivo')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre Original')),
                ('tamaño', models.PositiveIntegerField(verbose_name='Tamaño (bytes)')),
                ('subido_el', models.DateTimeField(auto_now_add=True, verbose_name='Subido el')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='solicitudes.solicitud', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Documento Adjunto',
                'verbose_name_plural': 'Documentos Adjuntos',
                'ordering': ['-subido_el'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use ABC-1234', regex='^[A-Z]{1,3}-\\d{4}$')], verbose_name='Placa')),
                ('tipo_vehiculo', models.CharField(choices=[('automovil', 'Automóvil'), ('camion', 'Camión'), ('camioneta', 'Camioneta'), ('motocicleta', 'Motocicleta'), ('equipo_especializado', 'Equipo Especializado')], max_length=50, verbose_name='Tipo de Vehículo')),
                ('conductor_nombre', models.CharField(max_length=200, verbose_name='Nombre del Conductor')),
                ('conductor_licencia', models.CharField(blank=True, max_length=20, verbose_name='Licencia de Conducir')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='solicitudes.solicitud', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'unique_together': {('solicitud', 'placa')},
            },
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['estado', '-creada_el'], name='solicitudes_estado_613a12_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['evaluador_asignado', 'estado'], name='solicitudes_evaluad_3d130e_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['vence_el'], name='solicitudes_vence_e_fffe18_idx'),
        ),
    ]
