# Generated by Django 5.2.1 on 2025-08-08 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_operacion', models.CharField(blank=True, help_text='Rol específico en esta operación (ej: Conductor Principal, Operador de Grúa, etc.)', max_length=100, verbose_name='Rol en la Operación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.personal', verbose_name='Personal')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_asignado', to='solicitudes.solicitud', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Personal de Solicitud',
                'verbose_name_plural': 'Personal de Solicitudes',
                'ordering': ['created_at'],
                'unique_together': {('solicitud', 'personal')},
            },
        ),
    ]
