# Generated by Django 5.2.1 on 2025-08-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0004_servicio_tipolicencia'),
        ('solicitudes', '0002_solicitudpersonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='servicios_solicitados',
            field=models.ManyToManyField(blank=True, help_text='Servicios específicos que la empresa requiere para esta solicitud', related_name='solicitudes', to='evaluacion.servicio', verbose_name='Servicios Solicitados'),
        ),
    ]
