# Generated by Django 5.2.1 on 2025-08-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_solicitud_servicios_solicitados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('sin_asignar', 'Sin Asignar'), ('pendiente', 'Pendiente de Revisión'), ('en_revision', 'En Revisión'), ('documentos_faltantes', 'Documentos Faltantes'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida'), ('escalada', 'Escalada a Supervisor')], default='borrador', max_length=25, verbose_name='Estado'),
        ),
    ]
