# Generated by Django 5.2.5 on 2025-09-28 19:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='puerto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='puerto',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='puerto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
        migrations.CreateModel(
            name='LugarPuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Lugar')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('tipo_lugar', models.CharField(choices=[('muelle', 'Muelle'), ('oficinas', 'Oficinas'), ('parqueo', 'Parqueo'), ('almacen', 'Almacén'), ('contenedores', 'Zona de Contenedores'), ('aduana', 'Aduana'), ('servicios', 'Servicios'), ('otro', 'Otro')], default='muelle', max_length=50, verbose_name='Tipo de Lugar')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('capacidad_maxima', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad Máxima')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('puerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to='solicitudes.puerto', verbose_name='Puerto')),
            ],
            options={
                'verbose_name': 'Lugar del Puerto',
                'verbose_name_plural': 'Lugares del Puerto',
                'ordering': ['puerto__nombre', 'nombre'],
                'unique_together': {('puerto', 'codigo')},
            },
        ),
    ]
