# Generated by Django 5.2.5 on 2025-09-29 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_puerto_descripcion_puerto_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='lugar_destino',
            field=models.ForeignKey(blank=True, help_text='Lugar específico dentro del puerto', null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.lugarpuerto', verbose_name='Lugar de Destino'),
        ),
    ]
