# Generated by Django 5.2.5 on 2025-09-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0006_configuracionemail_nombre_and_more'),
        ('solicitudes', '0006_solicitud_lugar_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivoacceso',
            name='servicios_relacionados',
            field=models.ManyToManyField(blank=True, help_text='Servicios que pueden usar este motivo de acceso', related_name='motivos_acceso', to='evaluacion.servicio', verbose_name='Servicios Relacionados'),
        ),
    ]
