# Generated by Django 5.2.5 on 2025-09-29 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_servicio_empresaservicio_fecha_expiracion_licencia_and_more'),
        ('solicitudes', '0007_add_servicios_relacionados_to_motivo_acceso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('cedula', 'Cédula de Identidad'), ('licencia_conducir', 'Licencia de Conducir'), ('certificado_medico', 'Certificado Médico'), ('certificado_antecedentes', 'Certificado de Antecedentes'), ('foto', 'Fotografía')], max_length=25, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(upload_to='documentos/personal/', verbose_name='Archivo')),
                ('numero_documento', models.CharField(blank=True, max_length=50, verbose_name='Número de Documento')),
                ('fecha_emision', models.DateField(blank=True, null=True, verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado')),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('subido_el', models.DateTimeField(auto_now_add=True, verbose_name='Subido el')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='empresas.personal')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_personales_verificados', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Documento Personal',
                'verbose_name_plural': 'Documentos Personales',
                'unique_together': {('personal', 'tipo_documento')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('registro', 'Registro de Vehículo'), ('seguro', 'Seguro Vehicular'), ('inspeccion_tecnica', 'Inspección Técnica'), ('permiso_circulacion', 'Permiso de Circulación'), ('certificado_gases', 'Certificado de Emisión de Gases')], max_length=25, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(upload_to='documentos/vehiculos/', verbose_name='Archivo')),
                ('numero_documento', models.CharField(blank=True, max_length=50, verbose_name='Número de Documento')),
                ('fecha_emision', models.DateField(blank=True, null=True, verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado')),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('subido_el', models.DateTimeField(auto_now_add=True, verbose_name='Subido el')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='solicitudes.vehiculo')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_vehiculos_verificados', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Documento Vehículo',
                'verbose_name_plural': 'Documentos Vehículos',
                'unique_together': {('vehiculo', 'tipo_documento')},
            },
        ),
    ]
