# Generated by Django 5.2.4 on 2025-11-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_documentopersonal_documentovehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='prioridad',
            field=models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('critica', 'Crítica'), ('vip', 'VIP Gubernamental')], default='normal', max_length=15, verbose_name='Prioridad'),
        ),
    ]
