# Generated by Django 4.2.16 on 2025-11-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_alter_solicitud_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='numero_imo',
            field=models.CharField(blank=True, help_text='Número de identificación IMO de la embarcación (7 dígitos)', max_length=20, null=True, verbose_name='Número IMO'),
        ),
    ]
