# Generated by Django 4.2.16 on 2025-11-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_add_numero_imo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='naviera',
            field=models.CharField(blank=True, help_text='Nombre de la empresa naviera propietaria de la embarcación', max_length=200, null=True, verbose_name='Naviera'),
        ),
    ]
