# Generated by Django 4.2.16 on 2025-11-23 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0009_add_documento_requerido_servicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0011_add_naviera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('recibido', 'Recibida'), ('sin_asignar', 'Sin Asignar'), ('pendiente', 'Pendiente de Revisión'), ('en_revision', 'En Revisión'), ('documentos_faltantes', 'Documentos Faltantes'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida'), ('escalada', 'Escalada a Supervisor')], default='borrador', max_length=25, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='DocumentoServicioSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='solicitudes/documentos_servicios/%Y/%m/', verbose_name='Archivo')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre Original del Archivo')),
                ('tamaño', models.PositiveIntegerField(verbose_name='Tamaño (bytes)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del Solicitante')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado')),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('comentario_verificacion', models.TextField(blank=True, verbose_name='Comentario de Verificación')),
                ('subido_el', models.DateTimeField(auto_now_add=True, verbose_name='Subido el')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('documento_requerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_subidos', to='evaluacion.documentorequeridoservicio', verbose_name='Documento Requerido')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_servicios', to='solicitudes.solicitud', verbose_name='Solicitud')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_servicios_verificados', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Documento de Servicio',
                'verbose_name_plural': 'Documentos de Servicios',
                'ordering': ['solicitud', 'documento_requerido__orden'],
                'unique_together': {('solicitud', 'documento_requerido')},
            },
        ),
    ]
