# Generated by Django 4.2.25 on 2026-01-08 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0012_add_documento_servicio_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('creacion', 'Solicitud Creada'), ('envio', 'Solicitud Enviada'), ('asignacion', 'Asignada a Evaluador'), ('inicio_revision', 'Revisión Iniciada'), ('documentos_faltantes', 'Documentos Faltantes'), ('documentos_completados', 'Documentos Completados'), ('aprobacion', 'Solicitud Aprobada'), ('rechazo', 'Solicitud Rechazada'), ('escalacion', 'Escalada a Supervisor'), ('cambio_estado', 'Cambio de Estado'), ('cambio_prioridad', 'Cambio de Prioridad'), ('reasignacion', 'Reasignada a Otro Evaluador'), ('comentario', 'Comentario Agregado'), ('nota_interna', 'Nota Interna'), ('documento_subido', 'Documento Subido'), ('documento_verificado', 'Documento Verificado'), ('documento_rechazado', 'Documento Rechazado'), ('vencimiento_proximo', 'Vencimiento Próximo'), ('vencida', 'Solicitud Vencida'), ('actualizacion', 'Información Actualizada')], max_length=30, verbose_name='Tipo de Evento')),
                ('titulo', models.CharField(help_text='Descripción breve del evento', max_length=200, verbose_name='Título del Evento')),
                ('descripcion', models.TextField(blank=True, help_text='Información adicional sobre el evento', verbose_name='Descripción Detallada')),
                ('metadata', models.JSONField(blank=True, help_text='Datos adicionales del evento en formato JSON (estado anterior, estado nuevo, etc.)', null=True, verbose_name='Metadata')),
                ('es_visible_solicitante', models.BooleanField(default=True, help_text='Si el solicitante puede ver este evento en su timeline', verbose_name='Visible para Solicitante')),
                ('es_interno', models.BooleanField(default=False, help_text='Solo visible para personal de evaluación', verbose_name='Evento Interno')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='solicitudes.solicitud', verbose_name='Solicitud')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que generó este evento (puede ser null para eventos automáticos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_solicitudes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Evento de Solicitud',
                'verbose_name_plural': 'Eventos de Solicitudes',
                'ordering': ['-creado_el'],
                'indexes': [models.Index(fields=['solicitud', '-creado_el'], name='solicitudes_solicit_c39931_idx'), models.Index(fields=['tipo_evento', '-creado_el'], name='solicitudes_tipo_ev_0c256c_idx'), models.Index(fields=['usuario', '-creado_el'], name='solicitudes_usuario_f5fa09_idx')],
            },
        ),
    ]
