# Generated by Django 4.2.16 on 2025-07-29 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código de Escalamiento')),
                ('tipo_escalamiento', models.CharField(choices=[('vip_gubernamental', 'VIP Gubernamental'), ('caso_complejo', 'Caso Complejo'), ('documentacion_especial', 'Documentación Especial'), ('solicitud_vencida', 'Solicitud Vencida'), ('discrepancia_grave', 'Discrepancia Grave'), ('revision_manual', 'Revisión Manual Requerida'), ('otros', 'Otros')], max_length=25, verbose_name='Tipo de Escalamiento')),
                ('prioridad', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad')),
                ('motivo', models.TextField(verbose_name='Motivo del Escalamiento')),
                ('descripcion_detallada', models.TextField(verbose_name='Descripción Detallada')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('resuelto', 'Resuelto'), ('reasignado', 'Reasignado'), ('cerrado', 'Cerrado')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('resolucion', models.TextField(blank=True, verbose_name='Resolución')),
                ('decision_tomada', models.CharField(blank=True, choices=[('aprobar', 'Aprobar Solicitud'), ('rechazar', 'Rechazar Solicitud'), ('solicitar_documentos', 'Solicitar Documentos Adicionales'), ('reasignar', 'Reasignar a Otro Evaluador'), ('otros', 'Otros')], max_length=50, verbose_name='Decisión Tomada')),
                ('tiempo_limite', models.DateTimeField(blank=True, null=True, verbose_name='Tiempo Límite')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalamientos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('escalado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalamientos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Escalado por')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalamientos_resueltos', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalamientos', to='solicitudes.solicitud', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Escalamiento',
                'verbose_name_plural': 'Escalamientos',
                'ordering': ['-creado_el'],
                'indexes': [models.Index(fields=['estado', '-creado_el'], name='supervisor__estado_1f8456_idx'), models.Index(fields=['asignado_a', 'estado'], name='supervisor__asignad_b2d0fa_idx'), models.Index(fields=['prioridad', '-creado_el'], name='supervisor__priorid_194ffe_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo_alerta', models.CharField(choices=[('solicitud_vip_venciendo', 'Solicitud VIP por Vencer'), ('evaluadores_sobrecargados', 'Evaluadores Sobrecargados'), ('discrepancias_acumuladas', 'Discrepancias Acumuladas'), ('sistema_actualizado', 'Sistema Actualizado'), ('error_sistema', 'Error del Sistema'), ('rendimiento_bajo', 'Rendimiento Bajo'), ('otros', 'Otros')], max_length=30, verbose_name='Tipo de Alerta')),
                ('nivel', models.CharField(choices=[('info', 'Información'), ('advertencia', 'Advertencia'), ('critico', 'Crítico')], default='info', max_length=15, verbose_name='Nivel')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('datos_adicionales', models.JSONField(blank=True, default=dict, verbose_name='Datos Adicionales')),
                ('creada_el', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('leida_el', models.DateTimeField(blank=True, null=True, verbose_name='Leída el')),
                ('dirigida_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Dirigida a')),
            ],
            options={
                'verbose_name': 'Alerta del Sistema',
                'verbose_name_plural': 'Alertas del Sistema',
                'ordering': ['-creada_el'],
                'indexes': [models.Index(fields=['dirigida_a', 'activa', '-creada_el'], name='supervisor__dirigid_cb2ea1_idx'), models.Index(fields=['nivel', 'activa'], name='supervisor__nivel_5dd207_idx')],
            },
        ),
    ]
