# Generated by Django 5.2.1 on 2025-08-08 18:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnc', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use XXX-XXXXX-X para RNC', regex='^\\d{3}-\\d{5}-\\d{1}$')], verbose_name='RNC')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use XXX-XXX-XXXX', regex='^\\d{3}-\\d{3}-\\d{4}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Empresa de Servicio',
                'verbose_name_plural': 'Empresas de Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('cedula', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use XXX-XXXXXXX-X para cédula', regex='^\\d{3}-\\d{7}-\\d{1}$')], verbose_name='Cédula')),
                ('cargo', models.CharField(blank=True, help_text='Ej: Conductor, Operador, Técnico, etc.', max_length=100, verbose_name='Cargo/Posición')),
                ('licencia_conducir', models.CharField(blank=True, help_text='Número de licencia de conducir si aplica', max_length=20, verbose_name='Licencia de Conducir')),
                ('telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use XXX-XXX-XXXX', regex='^\\d{3}-\\d{3}-\\d{4}$')], verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PersonalEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresaservicio', verbose_name='Empresa')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.personal', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Personal de Empresa',
                'verbose_name_plural': 'Personal de Empresas',
                'ordering': ['-fecha_inicio'],
                'unique_together': {('personal', 'empresa')},
            },
        ),
    ]
