# Generated by Django 5.2.1 on 2025-08-09 01:41

import empresas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='empresaservicio',
            name='fecha_expiracion_licencia',
            field=models.DateField(default=empresas.models.get_default_expiration_date, help_text='Fecha hasta la cual la licencia es válida', verbose_name='Fecha de Expiración de Licencia'),
        ),
        migrations.AddField(
            model_name='empresaservicio',
            name='numero_licencia',
            field=models.CharField(default='TEMP-LICENSE-001', help_text='Número único de licencia de operación', max_length=50, unique=True, verbose_name='Número de Licencia'),
        ),
        migrations.AddField(
            model_name='empresaservicio',
            name='servicios_autorizados',
            field=models.ManyToManyField(blank=True, help_text='Servicios que la empresa está autorizada a ofrecer', to='empresas.servicio', verbose_name='Servicios Autorizados'),
        ),
    ]
