# Generated by Django 4.2.25 on 2026-01-07 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_servicio_empresaservicio_fecha_expiracion_licencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='pasaporte',
            field=models.CharField(blank=True, help_text='Para extranjeros sin cédula dominicana', max_length=20, null=True, verbose_name='Pasaporte'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='cedula',
            field=models.CharField(blank=True, help_text='Para dominicanos', max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use XXX-XXXXXXX-X para cédula', regex='^\\d{3}-\\d{7}-\\d{1}$')], verbose_name='Cédula'),
        ),
    ]
